package Exception;

public class RuntimeExceptionTest {
	public static void main(String[] args) {
		
		int[] array = new int[3];
//		String nullString = "Hello null";
		
		//null flow check
//		if(nullString !=null)
//			System.out.println(	   nullString.charAt(0));
//		
//		int[] negativeArray = new int[-5];
//		int index= 2;
//		if(index < array.length)
//			
//		System.out.println(array[index]);
//		else 
//			System.err.println("Array index out of bound");
		double op1 = 10;
		double op2 = 0;
		if(op2 != 0)
		
		System.out.println(op1/op2);//Arithmetic Exception
		else
			System.err.println("Operand 2 is 0 - cant divided opt");
		
		System.out.println("Other Systems are working.");
		
		
//		try {
//			String nullString = null;
//			nullString.charAt(0);
//			
//			int[] negativeArray = new int[-5];
//			System.out.println(array[5]);
//			System.out.println(10/0);//Arithmetic Exception
//			
//		} catch (ArithmeticException e) {
//			System.out.println("Inside Arithmetic Exception");
//			// TODO: handle exception
//			e.printStackTrace();//hote ko htote pay ya mal dar mha trip lite lox ya mal
//		}catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Inside ArrayIndexOutOfBoundsException Exception");
//			// TODO: handle exception
//			e.printStackTrace();
//		}catch (Exception e) {// always close
//			// TODO: handle exception
//			System.out.println("Indide Exception");
//			e.printStackTrace();
//		}catch (Throwable e) {
//			// TODO: handle exception
//		}
		
		
		
		
		
	}

}
